### ISSUE TITLE
mcp_info.py examples refer to task as mcp_facts

### ISSUE THREAD

**Issue by rhogge-JT** [nttmcp/mcp_collection#12]
Hi, just a minor issue i noticed, the EXAMPLES section of the mcp_info module refers to the task module as mcp_facts rather than mcp_info.

`EXAMPLES = '''
- hosts: 127.0.0.1
  connection: local
  collections:
    - nttmcp.mcp
  tasks:

  - name: GET a list of MCPs
    mcp_facts:
      region: na

  - name: Get details on a specific MCP
    mcp_facts:
      region: na
      name: NA9
'''
`

Not a massive problem but a bit misleading for those who may be using this as a reference point.

**Comment by kensinfield** [comment]
good catch thanks.. will update.

**Comment by kensinfield** [comment]
Hi,

you should be good to update to v1.0.9 of the modules to resolve both issues you raised (and a one I found with filtering VIP SSL profiles/certs/chains via network_domain).

ansible-galaxy collection install nttmcp.mcp -f

Thanks,
Ken.
